### ISSUE TITLE
Readme文档错误

### ISSUE THREAD

**Issue by crazy965** [dingxiangtech/dx-signer#5]
在命令行界面一栏中，将dx-signer.jar 写成了dx-signer.apk。

现为：
java -jar dx-signer.apk sign [--option value]+
应为：
java -jar dx-signer.jar sign [--option value]+

**Comment by pxb1988** [comment]
修订已经提交啦，感谢
https://github.com/dingxiangtech/dx-signer/commit/07e0e7f33dc77c8a65841b9b89761e9d23da870d
